### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WillTheDeveloper**

### CODE REVIEW

**Review by mauro-balades — CHANGES_REQUESTED** [review]
Hm... I aprove it but... Maybe we should change this repos to @cheese-official. What do you think?

**Comment by WillTheDeveloper** [comment]
Yeah, I agree. Once it actually becomes a bit more official and less of a meme, then it will get moved :)

**Comment by mauro-balades** [comment]
alr

**Comment by WillTheDeveloper** [comment]
Yes sirrrrr

**Pull request merged**
